CREATE TABLE job_application (
    id                      BIGINT       NOT NULL AUTO_INCREMENT,
    first_name              VARCHAR(255),
    last_name               VARCHAR(255),
    email                   VARCHAR(255),
    phone                   VARCHAR(255),
    address                 VARCHAR(255),
    city                    VARCHAR(255),
    state                   VARCHAR(255),
    zip                     VARCHAR(255),
    position_applying       VARCHAR(255),
    employment_type         VARCHAR(255),
    desired_start_date      VARCHAR(255),
    hours_available         INT,
    has_previous_experience VARCHAR(255),
    previous_employer       VARCHAR(255),
    previous_job_title      VARCHAR(255),
    previous_start_date     VARCHAR(255),
    previous_end_date       VARCHAR(255),
    reason_for_leaving      VARCHAR(255),
    additional_experience   VARCHAR(255),
    why_join                TEXT,
    about_yourself          TEXT,
    how_did_you_hear        VARCHAR(255),
    resume_file_name        VARCHAR(255),
    PRIMARY KEY (id)
);
